services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secretpassword}
      POSTGRES_DB: ${DB_NAME:-iron_db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-iron_db}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  init-db:
    image: postgres:15-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secretpassword}
    volumes:
      - ./init.sql:/init.sql:ro
    command: [
      "sh",
      "-c",
      "psql -h db -U ${DB_USER:-admin} -d ${DB_NAME:-iron_db} -f /init.sql"
    ]
    restart: "no"

  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"

  bot:
    build: 
      context: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_DSN: "postgresql://${DB_USER:-admin}:${DB_PASSWORD:-secretpassword}@db:5432/${DB_NAME:-iron_db}"
      NATS_URL: "nats://nats:4222"
      SCRAPER_BASE_URL: "http://scraper:3000"
    depends_on:
      init-db:
        condition: service_completed_successfully
      nats:
        condition: service_started
      scraper:
        condition: service_started

  scraper:
    build:
      context: ./scraper/scraper-service
    environment:
      DATABASE_URL: "postgresql://${DB_USER:-admin}:${DB_PASSWORD:-secretpassword}@db:5432/${DB_NAME:-iron_db}"
      NATS_URL: "nats://nats:4222"
      PARSER_URL: "http://scraper-parser:8080"
    ports:
      - "3000:3000"
    depends_on:
      init-db:
        condition: service_completed_successfully
      nats:
        condition: service_started
      scraper-parser:
        condition: service_started

  scraper-parser:
    build:
      context: ./scraper
      dockerfile: Dockerfile.parser
    ports:
      - "8080:8080"
      
  gateway:
    build:
      context: ./gateway
    environment:
      NATS_URL: "nats://nats:4222"
      PORT: "8000"
    ports:
      - "8000:8000"
    depends_on:
      nats:
        condition: service_started

  site:
    build:
      context: ./site
    environment:
      NATS_URL: "nats://nats:4222"
    ports:
      - "8085:80"
    depends_on:
      nats:
        condition: service_started

volumes:
  db-data:
